[package]
name = "streamz-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
rand = "0.8"
tokio = { version = "1", features = ["full"] }
rodio = "0.17"
cpal = "0.15"
crossterm = "0.27"
ndarray-npy = "0.8"
hound = "3"

[[bin]]
name = "StreamZ"
path = "src/main.rs"
